server:
  port: 8080

spring:
  application:
    name: conta-service

  # CQRS: o conta só conecta nos 2 bancos DELE (nenhuma conexão com cliente_db)
  datasource:               # banco de ESCRITA (CUD)
    jdbc-url: jdbc:postgresql://postgres:5432/conta_cud_db
    username: dac
    password: dac
    driver-class-name: org.postgresql.Driver

  datasource-read:          # banco de LEITURA (R)
    jdbc-url: jdbc:postgresql://postgres:5432/conta_r_db
    username: dac
    password: dac
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health