server:
  port: 8080

spring:
  application:
    name: conta-service

  datasource:
    url: jdbc:postgresql://postgres:5432/dac
    username: dac
    password: dac
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health
