server:
  port: 8080
spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth_db
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret: co\saed<>:??/|\hfIWU|Ef324h$@$*&(14lk\\d[-0]?;d.adp224(^c`{)}}))/\@!#
  expiration: 600000 # 600000ms = 10 minutos
