server:
  port: 8080
spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth_db
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret: bantads-secret-key-super-segura-2026
  expiration: 86400000