server:
  port: 8080
spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth_db
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret: ${JWT_SECRET:DAC_DEV_SECRET_2026_32_CHARS_MINIMUM_KEY}
  expiration: 600000 # 600000ms = 10 minutos
